services:
  rchan6:
    image: ghcr.io/rtainjapan/rchan6:latest
    container_name: rchan6
    environment:
      - DISCORD_CLIENT_ID=
      - DISCORD_SCOPE=
      - DISCORD_ALLOW_ROLES=
      - DISCORD_GUILD_ID=
      - DISCORD_TOKEN=
      - PORT=80
    restart: always
    # 外向けのポート:中のポート
    ports:
      - 3000:80
